package com.adhils.fitness.core

object Catalog {
    private fun ex(id: String, name: String, pattern: String, equipment: String, muscles: String,
        setup: String, movement: String, camera: String? = null, view: String = "Side",
        timed: Boolean = false, perHand: Boolean = false) =
        Exercise(id, name, pattern, equipment, muscles, listOf(setup, movement,
            "Choose a comfortable range. Stop the set if you feel pain."),
            "Breathe steadily; exhale through the effort.", camera, view, timed, perHand)
    val exercises = listOf(
        // Squat pattern
        ex("goblet-squat", "Goblet squat", "Squat", "Dumbbells", "Quads · Glutes",
            "Hold one dumbbell close to your chest. Stand with feet comfortably apart.",
            "Bend your knees and hips, then return to standing without bouncing.", "squat"),
        ex("bodyweight-squat", "Bodyweight squat", "Squat", "Bodyweight", "Quads · Glutes",
            "Stand with feet comfortably apart and arms forward for balance.",
            "Lower in control and return to standing.", "squat"),
        ex("reverse-lunge", "Reverse lunge", "Squat", "Bodyweight", "Quads · Glutes",
            "Stand tall near a stable support if needed.",
            "Step back, lower through a comfortable range, return, and alternate sides."),
        ex("dumbbell-split-squat", "Dumbbell split squat", "Squat", "Dumbbells", "Quads · Glutes",
            "Stand in a staggered stance holding dumbbells by your sides.",
            "Lower your back knee toward the floor in control, then press through your front foot.", perHand = true),
        ex("bulgarian-split-squat", "Bulgarian split squat", "Squat", "Bench", "Quads · Glutes",
            "Rest the top of one foot behind you on a bench and stand tall on the front leg.",
            "Lower under control until your front thigh is near parallel, then drive back up."),
        ex("sumo-squat", "Dumbbell sumo squat", "Squat", "Dumbbells", "Quads · Glutes · Inner thighs",
            "Take a wide stance with toes angled slightly outward, holding a dumbbell in front.",
            "Sit your hips down while keeping knees aligned with your toes, then stand tall.", "squat"),
        ex("step-up", "Bench step-up", "Squat", "Bench", "Quads · Glutes",
            "Place one whole foot firmly on a stable bench.",
            "Press through your lead heel to stand tall on the bench, then step down slowly."),
        ex("band-squat", "Resistance band squat", "Squat", "Bands", "Quads · Glutes",
            "Stand on the band with feet shoulder-width apart and hold the handles at shoulder height.",
            "Squat down with chest proud and drive back up against the band tension.", "squat"),
        ex("wall-sit", "Wall sit hold", "Squat", "Bodyweight", "Quads · Glutes",
            "Lean your back flat against a smooth wall and slide down until knees are comfortably bent.",
            "Hold your position with feet flat and weight evenly distributed.", timed = true),

        // Hinge pattern
        ex("rdl", "Dumbbell Romanian deadlift", "Hinge", "Dumbbells", "Hamstrings · Glutes",
            "Stand with a dumbbell in each hand and a slight bend in your knees.",
            "Move your hips back, keeping the weights close. Return to standing in control.", "rdl", perHand = true),
        ex("bridge", "Glute bridge", "Hinge", "Bodyweight", "Glutes · Hamstrings",
            "Lie on your back with knees bent and feet flat.",
            "Lift your hips, pause comfortably, then lower."),
        ex("single-leg-rdl", "Single-leg Romanian deadlift", "Hinge", "Dumbbells", "Hamstrings · Glutes · Balance",
            "Balance on one leg with a slight knee bend, holding a dumbbell in the opposite hand.",
            "Hinge at the hips while extending your free leg back, then return to standing.", perHand = true),
        ex("hip-thrust", "Bench hip thrust", "Hinge", "Bench", "Glutes · Hamstrings",
            "Rest your upper back against the edge of a stable bench with feet planted hip-width apart.",
            "Drive through your heels to extend your hips until level, pause briefly, and lower in control."),
        ex("single-leg-bridge", "Single-leg glute bridge", "Hinge", "Bodyweight", "Glutes · Hamstrings",
            "Lie on your back with one foot planted and the other knee raised toward your chest.",
            "Press through your planted heel to lift your hips, lower slowly, and complete both sides."),
        ex("dumbbell-swing", "Dumbbell hip hinge swing", "Hinge", "Dumbbells", "Glutes · Hamstrings · Core",
            "Stand with feet slightly wider than hips holding one dumbbell securely with both hands.",
            "Hinge hips back and drive them forward crisply to swing the dumbbell to chest height."),
        ex("band-rdl", "Resistance band Romanian deadlift", "Hinge", "Bands", "Hamstrings · Glutes",
            "Stand on the center of a resistance band and grasp both ends with knees softly bent.",
            "Push your hips back with a flat back, then squeeze glutes to return to standing.", "rdl"),
        ex("good-morning", "Bodyweight good morning", "Hinge", "Bodyweight", "Hamstrings · Lower back",
            "Stand tall with fingertips lightly behind your ears and knees softly unlocked.",
            "Push your hips backward while keeping your spine neutral, then return to standing.", "rdl"),

        // Push pattern
        ex("press", "Dumbbell shoulder press", "Push", "Dumbbells", "Shoulders · Triceps",
            "Stand with dumbbells near shoulder height and feet planted.",
            "Press overhead through a comfortable range, then lower in control.", "press", "Front", perHand = true),
        ex("pushup", "Push-up", "Push", "Bodyweight", "Chest · Triceps · Core",
            "Place hands on the floor near shoulder width with legs extended.",
            "Lower and press up with shoulders, hips, and ankles moving together.", "pushup"),
        ex("floor-press", "Dumbbell floor press", "Push", "Dumbbells", "Chest · Triceps",
            "Lie on the floor with knees bent and dumbbells near your chest.",
            "Press up and lower until your upper arms gently meet the floor.", perHand = true),
        ex("wall-pushup", "Wall push-up", "Push", "Bodyweight", "Chest · Triceps",
            "Stand facing a wall with palms at shoulder height.",
            "Bend elbows toward the wall and press back."),
        ex("bench-press", "Dumbbell bench press", "Push", "Bench", "Chest · Triceps · Shoulders",
            "Lie flat on a bench with feet planted and dumbbells held above your chest.",
            "Lower the dumbbells with elbows at a 45-degree angle, then press back up.", perHand = true),
        ex("incline-press", "Incline dumbbell press", "Push", "Bench", "Upper chest · Shoulders · Triceps",
            "Sit on an angled bench with back supported and dumbbells at shoulder level.",
            "Press the weights upward until arms are extended, then lower slowly.", perHand = true),
        ex("incline-pushup", "Incline bench push-up", "Push", "Bench", "Chest · Triceps · Core",
            "Place your hands shoulder-width apart on the edge of a sturdy bench.",
            "Lower your chest toward the bench while keeping your body straight, then press up.", "pushup"),
        ex("knee-pushup", "Knee push-up", "Push", "Bodyweight", "Chest · Triceps",
            "Kneel on a mat with hands slightly wider than shoulders and hips aligned with knees.",
            "Lower your chest toward the floor in control and press back to the top.", "pushup"),
        ex("pike-pushup", "Pike push-up", "Push", "Bodyweight", "Shoulders · Triceps",
            "Start in an inverted V position with hips high and hands shoulder-width apart.",
            "Bend your elbows to lower the top of your head toward the floor, then press back up."),
        ex("arnold-press", "Dumbbell Arnold press", "Push", "Dumbbells", "Shoulders · Triceps",
            "Hold dumbbells at chin height with palms facing toward you.",
            "Rotate your palms outward as you press overhead, then reverse on the way down.", "press", "Front", perHand = true),
        ex("band-press", "Resistance band overhead press", "Push", "Bands", "Shoulders · Triceps",
            "Stand on the band and bring the handles to shoulder height with palms forward.",
            "Press the handles straight overhead without arching your lower back, then lower.", "press", "Front"),
        ex("band-chest-press", "Resistance band chest press", "Push", "Bands", "Chest · Triceps",
            "Wrap the band behind your upper back or anchor it behind you at chest height.",
            "Press both hands forward until arms are extended, then return with control."),

        // Pull pattern
        ex("row", "One-arm dumbbell row", "Pull", "Dumbbells", "Back · Biceps",
            "Support one hand on a stable surface and hold a dumbbell in the other.",
            "Pull the elbow toward your hip, lower in control, then switch sides.", perHand = true),
        ex("curl", "Dumbbell curl", "Pull", "Dumbbells", "Biceps",
            "Stand with arms by your sides and a dumbbell in each hand.",
            "Bend your elbows without swinging, then lower slowly.", perHand = true),
        ex("band-row", "Resistance band row", "Pull", "Bands", "Back · Biceps",
            "Secure a band to a suitable anchor according to its instructions.",
            "Pull your elbows back and return with control."),
        ex("band-pull-apart", "Band pull-apart", "Pull", "Bands", "Upper back",
            "Hold a light band in front of you.",
            "Move hands apart through a comfortable range and return slowly."),
        ex("bent-over-row", "Two-arm bent-over dumbbell row", "Pull", "Dumbbells", "Back · Lats · Biceps",
            "Hinge forward at the hips with a flat back, holding dumbbells beneath your shoulders.",
            "Row both dumbbells toward your lower ribs, pause briefly, and lower in control.", perHand = true),
        ex("chest-supported-row", "Chest-supported dumbbell row", "Pull", "Bench", "Upper back · Lats",
            "Rest your chest against an incline bench with arms hanging straight down.",
            "Pull the dumbbells back toward your hips while squeezing your shoulder blades.", perHand = true),
        ex("hammer-curl", "Dumbbell hammer curl", "Pull", "Dumbbells", "Biceps · Forearms",
            "Stand tall holding dumbbells with palms facing each other.",
            "Curl the weights up while keeping your palms neutral and elbows tucked.", perHand = true),
        ex("incline-curl", "Incline dumbbell curl", "Pull", "Bench", "Biceps",
            "Sit back on an incline bench with arms hanging straight down by your sides.",
            "Curl the dumbbells upward without moving your upper arms, then lower fully.", perHand = true),
        ex("reverse-fly", "Dumbbell rear delt fly", "Pull", "Dumbbells", "Rear shoulders · Upper back",
            "Hinge forward at the hips holding light dumbbells beneath your chest.",
            "Sweep your arms out to the sides with a slight elbow bend, then lower slowly.", perHand = true),
        ex("band-face-pull", "Resistance band face pull", "Pull", "Bands", "Rear shoulders · Upper back",
            "Anchor a band at upper-chest or eye level and hold both ends.",
            "Pull the band toward your forehead while keeping elbows high and rotating shoulders back."),
        ex("band-curl", "Resistance band bicep curl", "Pull", "Bands", "Biceps",
            "Stand on the center of the band and hold the ends with palms facing forward.",
            "Curl your hands toward your shoulders while keeping elbows pinned to your sides."),
        ex("superman-pull", "Prone Y-T-W back raise", "Pull", "Bodyweight", "Upper back · Lower back",
            "Lie face down on a mat with forehead resting lightly and arms extended.",
            "Lift your arms and chest slightly while squeezing your shoulder blades back and down."),

        // Core pattern
        ex("plank", "Forearm plank", "Core", "Bodyweight", "Core",
            "Place forearms on the floor with elbows under shoulders.",
            "Hold a steady shoulder-to-ankle line while breathing.", "plank", timed = true),
        ex("bird-dog", "Bird dog", "Core", "Bodyweight", "Core · Back",
            "Start on hands and knees.",
            "Reach an opposite arm and leg, return, and alternate sides."),
        ex("dead-bug", "Dead bug", "Core", "Bodyweight", "Core",
            "Lie on your back with arms raised and knees bent.",
            "Slowly extend an opposite arm and leg, return, and switch sides."),
        ex("side-plank", "Side forearm plank", "Core", "Bodyweight", "Obliques · Core",
            "Lie on your side with your forearm directly beneath your shoulder and feet stacked or staggered.",
            "Lift your hips to form a straight line from shoulder to ankle and hold.", timed = true),
        ex("hollow-hold", "Hollow body hold", "Core", "Bodyweight", "Core",
            "Lie on your back and press your lower back firmly into the floor.",
            "Lift your shoulders and legs to a comfortable angle while keeping your lower back flat.", timed = true),
        ex("mountain-climber", "Controlled mountain climber", "Core", "Bodyweight", "Core · Hip flexors",
            "Start in a high plank position with hands directly under shoulders.",
            "Draw one knee toward your chest at a controlled pace, return, and alternate sides.", timed = true),
        ex("russian-twist", "Seated torso rotation", "Core", "Bodyweight", "Obliques · Core",
            "Sit tall on the floor with knees bent and heels lightly resting on the mat.",
            "Lean back slightly with a straight spine and rotate your torso smoothly side to side."),
        ex("suitcase-hold", "Single-arm suitcase hold", "Core", "Dumbbells", "Obliques · Grip · Core",
            "Stand tall holding a moderately heavy dumbbell in one hand at your side.",
            "Brace your core to prevent leaning and hold steady before switching sides.", timed = true, perHand = true),
        ex("pallof-press", "Band Pallof press", "Core", "Bands", "Core · Obliques",
            "Anchor a band at chest height and stand sideways to the anchor holding the band at your chest.",
            "Press the band straight out in front of you, resisting rotation, then return."),

        // Accessory pattern
        ex("calf-raise", "Calf raise", "Accessory", "Bodyweight", "Calves",
            "Stand near a stable support.",
            "Raise your heels, pause, and lower in control."),
        ex("lateral-raise", "Dumbbell lateral raise", "Accessory", "Dumbbells", "Shoulders",
            "Stand with light dumbbells by your sides.",
            "Raise arms outward through a comfortable range without swinging.", perHand = true),
        ex("weighted-calf-raise", "Dumbbell calf raise", "Accessory", "Dumbbells", "Calves",
            "Stand tall holding dumbbells at your sides with feet hip-width apart.",
            "Rise onto the balls of your feet, pause at the top, and lower slowly.", perHand = true),
        ex("front-raise", "Dumbbell front raise", "Accessory", "Dumbbells", "Front shoulders",
            "Stand holding light dumbbells in front of your thighs with palms facing down.",
            "Lift the weights to shoulder height with a soft elbow bend, then lower with control.", perHand = true),
        ex("tricep-extension", "Overhead dumbbell tricep extension", "Accessory", "Dumbbells", "Triceps",
            "Stand or sit tall holding one dumbbell overhead with both hands around the top bell.",
            "Keep elbows pointed forward as you lower the weight behind your head, then extend."),
        ex("tricep-kickback", "Dumbbell tricep kickback", "Accessory", "Dumbbells", "Triceps",
            "Hinge forward at the hips and tuck your upper arms parallel to your torso.",
            "Extend your forearms straight back until arms are straight, then return slowly.", perHand = true),
        ex("bench-dip", "Bench tricep dip", "Accessory", "Bench", "Triceps · Shoulders",
            "Sit on the edge of a stable bench with hands gripping beside your hips and knees bent.",
            "Lower your hips slightly in front of the bench to a comfortable elbow bend, then press up."),
        ex("shrug", "Dumbbell shrug", "Accessory", "Dumbbells", "Upper traps",
            "Stand tall holding dumbbells at your sides with arms relaxed.",
            "Elevate your shoulders straight up toward your ears, pause briefly, and lower.", perHand = true),
        ex("band-pushdown", "Resistance band tricep pushdown", "Accessory", "Bands", "Triceps",
            "Anchor a band high or loop it over a secure support and hold both ends with elbows tucked.",
            "Extend your forearms downward until straight, squeeze your triceps, and return."),
        ex("band-lateral-raise", "Resistance band lateral raise", "Accessory", "Bands", "Shoulders",
            "Stand on the middle of a light band and hold the ends at your sides.",
            "Raise your arms out to shoulder height with a slight elbow bend, then lower."),

        // Warm-up & Mobility
        ex("march", "Easy marching", "Warm-up", "Bodyweight", "Whole body",
            "Stand with space around you.",
            "March at an easy pace while moving your arms.", timed = true),
        ex("arm-circles", "Arm circles & shoulder rolls", "Warm-up", "Bodyweight", "Shoulders · Upper back",
            "Stand tall with feet hip-width apart and arms extended out to your sides.",
            "Make controlled forward and backward circles, gradually increasing range.", timed = true),
        ex("hip-openers", "Standing hip openers", "Warm-up", "Bodyweight", "Hips · Glutes",
            "Stand tall near a wall or support for balance.",
            "Lift one knee and rotate it outward in a smooth arc, alternating legs.", timed = true),
        ex("inchworm", "Walkout inchworm", "Warm-up", "Bodyweight", "Hamstrings · Core · Shoulders",
            "Stand at the back of your mat with knees softly bent.",
            "Hinge down, walk your hands out to a plank, pause, and walk hands back to standing.", timed = true),
        ex("cat-cow", "Cat–cow mobility", "Mobility", "Bodyweight", "Back",
            "Start on hands and knees.",
            "Gently move through a comfortable back range without forcing end positions.", timed = true),
        ex("thoracic-rotation", "Open-book thoracic rotation", "Mobility", "Bodyweight", "Upper back · Chest",
            "Lie on your side with knees bent at 90 degrees and arms resting together in front.",
            "Sweep your top arm across your chest toward the floor while breathing out, then return.", timed = true),
        ex("worlds-greatest-stretch", "Lunge & reach mobility", "Mobility", "Bodyweight", "Hips · Hamstrings · Upper back",
            "Step forward into a comfortable lunge and place your inside hand on the floor.",
            "Rotate your torso and reach your other arm toward the ceiling, then switch sides.", timed = true),
        ex("childs-pose", "Child’s pose breathing", "Mobility", "Bodyweight", "Back · Shoulders · Hips",
            "Kneel on a mat, sit your hips back toward your heels, and reach your arms forward.",
            "Breathe deeply into your back and ribs while relaxing your shoulders.", timed = true)
    )
    val byId = exercises.associateBy { it.id }
    fun get(id: String): Exercise = requireNotNull(byId[id]) { "Unknown exercise: $id" }
    fun alternatives(id: String, profile: Profile) = exercises.filter {
        it.id != id && it.pattern == get(id).pattern && it.id !in profile.excluded &&
        (it.equipment == "Bodyweight" || it.equipment in profile.equipment)
    }
}
